version: 2.1

jobs:
  test:
    docker:
      - image: gcc:9.2.0

    steps:
      - checkout

      - run:
          name: Update APT
          command: |
            apt update

      - run:
          name: Install Bazel
          command: |
            apt install -y bash-completion
            wget https://github.com/bazelbuild/bazel/releases/download/4.2.0/bazel_4.2.0-linux-x86_64.deb
            dpkg -i bazel_4.2.0-linux-x86_64.deb

      - run:
          name: Execute tests
          command: |
            bazel test //...

workflows:
  test:
    jobs:
      - test